name: Deploy via FTP

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'on push sur main

jobs:
  deploy:
    name: 🚀 Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion FTP et Déploiement
      - name: 📂 Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}       # Adresse du serveur FTP
          username: ${{ secrets.FTP_USERNAME }}   # Nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }}   # Mot de passe FTP
          local-dir: ./                           # Dossier source (à ajuster si besoin)
          server-dir: /home/konan/abrahamkonany/               # Dossier distant (adapter selon l'hébergement)

